# Generated by Django 4.0.6 on 2022-07-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLACES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Логин')),
                ('gmail', models.CharField(max_length=255, verbose_name='Почта')),
                ('password1', models.CharField(max_length=255, verbose_name='Пароль')),
                ('password2', models.CharField(max_length=255, verbose_name='Повторите пароль')),
                ('PLACE_NAME', models.CharField(max_length=255, verbose_name='Название учреждения')),
                ('PLACE_ADRES', models.CharField(max_length=255, verbose_name='Адрес')),
                ('FIO_DIR', models.CharField(max_length=255, verbose_name='ФИО Директора учреждения')),
                ('PLACE_CONTACT_NUMBER', models.CharField(max_length=255, verbose_name='Контактный номер')),
                ('DOCUMENTS_DLYA_PRIEMA', models.CharField(max_length=255, verbose_name='Документы для приема')),
                ('PLACE_PHOTO', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото учреждения')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Учреждения',
                'verbose_name_plural': 'Учреждения',
                'ordering': ['PLACE_NAME'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EVENT_NAME', models.CharField(max_length=255)),
                ('EVENT_CREATER', models.CharField(max_length=255)),
                ('PROTOCOL', models.CharField(max_length=255)),
                ('DATE_START', models.CharField(max_length=255)),
                ('DATE_END', models.CharField(max_length=255)),
                ('PHOTO_FROM_EVENT', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('Svyaz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.places')),
            ],
            options={
                'verbose_name': 'События',
                'verbose_name_plural': 'События',
                'ordering': ['EVENT_NAME'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=255, verbose_name='Имя')),
                ('LAST_NAME', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('IIN', models.CharField(max_length=255, verbose_name='ИИН')),
                ('WORK_PLACE', models.TextField(blank=True, verbose_name='Место работы')),
                ('JOB_TITLE', models.TextField(blank=True, verbose_name='Должность')),
                ('PHOTO_3x4', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото 3х4')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('Svyaz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.places', verbose_name='Повторить место работы')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['FIRST_NAME'],
            },
        ),
    ]
